// Auto-generated by scripts/update-git-log.sh — do not edit manually
export const gitCommits = [
  { hash: '1892edd', message: 'Add vim file editor with virtual filesystem support', date: '2026-02-13', author: 'otisscott' },
  { hash: '2db1397', message: 'Fix backspace leaving padding when cursor is mid-line', date: '2026-02-12', author: 'otisscott' },
  { hash: '15ff982', message: 'Rebuild favicon with tighter crop and multi-size ICO (16/32/48px)', date: '2026-02-12', author: 'Otis Scott' },
  { hash: '5dd9f3b', message: 'Remove stale screenshot script and placeholder content', date: '2026-02-12', author: 'Otis Scott' },
  { hash: '7b84f3d', message: 'Switch from npm to bun runtime', date: '2026-02-12', author: 'Otis Scott' },
  { hash: '8d2e9c4', message: 'Upgrade to Node.js 24 LTS (Krypton)', date: '2026-02-12', author: 'Otis Scott' },
];
