#!/usr/bin/env bash
# Auto-generate git log data for the terminal portfolio.
# Called by pre-commit hook.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
OUTPUT="$REPO_ROOT/lib/filesystem/git-log-data.ts"

entries=""
while IFS='|' read -r hash subject date author; do
  [ -z "$hash" ] && continue
  # Escape single quotes in subject/author
  subject="${subject//\'/\\\'}"
  author="${author//\'/\\\'}"
  entries+="  { hash: '${hash}', message: '${subject}', date: '${date}', author: '${author}' },
"
done < <(git log --format='%h|%s|%as|%an' -6)

cat > "$OUTPUT" << EOF
// Auto-generated by scripts/update-git-log.sh — do not edit manually
export const gitCommits = [
${entries}];
EOF
