#!/usr/bin/env bash
# Auto-generate git log data for the terminal portfolio.
# Runs as part of `build` so the deployed `gl` output always matches HEAD.
#
# Never fails the build: if git history is unavailable (no git binary, not a
# repo, or a clone too shallow to read), the committed file is left as-is.

set -uo pipefail

if ! command -v git >/dev/null 2>&1; then
  echo "update-git-log: git not found, keeping committed data" >&2
  exit 0
fi

if ! REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "update-git-log: not a git repo, keeping committed data" >&2
  exit 0
fi

OUTPUT="$REPO_ROOT/lib/filesystem/git-log-data.ts"

# Skip merges and dependabot bumps — `gl` should show real work, not CI noise.
GIT_LOG_ARGS=(--no-merges --perl-regexp --author='^(?!dependabot)' -6)

if ! log="$(git log "${GIT_LOG_ARGS[@]}" --format='%h|%s|%as|%an' 2>/dev/null)" || [ -z "$log" ]; then
  echo "update-git-log: no readable history, keeping committed data" >&2
  exit 0
fi

# CI providers (Vercel included) clone shallow. A truncated log would be worse
# than the committed data, so only overwrite when we got the full six.
if [ "$(git rev-parse --is-shallow-repository 2>/dev/null)" = "true" ] &&
   [ "$(printf '%s\n' "$log" | wc -l)" -lt 6 ]; then
  echo "update-git-log: shallow clone, keeping committed data" >&2
  exit 0
fi

entries=""
while IFS='|' read -r hash subject date author; do
  [ -z "$hash" ] && continue
  # Escape backslashes first, then single quotes, so the emitted TS parses
  subject="${subject//\\/\\\\}"; subject="${subject//\'/\\\'}"
  author="${author//\\/\\\\}"; author="${author//\'/\\\'}"
  entries+="  { hash: '${hash}', message: '${subject}', date: '${date}', author: '${author}' },
"
done <<< "$log"

cat > "$OUTPUT" << EOF
// Auto-generated by scripts/update-git-log.sh — do not edit manually
export const gitCommits = [
${entries}];
EOF
